#include "init.h"
void exception0()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
    halt();
}

void exception1()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception2()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception3()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception4()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception5()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception6()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception7()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception8()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception9()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception10()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception11()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception12()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception13()
{
    print("#GP\n",0xb);
}

void exception14()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception15()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception16()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception17()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception18()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception19()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception20()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception21()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception22()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception23()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception24()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception25()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception26()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception27()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception28()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception29()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception30()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception31()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}

void exception32()
{
    print(__FUNCTION__,0xb);
    print("\n",0xb);
}
